// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   mobileclient/v1
// Description:
//   This is an API

#if GTLR_BUILT_AS_FRAMEWORK
  #import "GTLR/GTLRObject.h"
#else
  #import "GTLRObject.h"
#endif

#if GTLR_RUNTIME_VERSION != 3000
#error This file was generated by a different version of ServiceGenerator which is incompatible with this GTLR library source.
#endif

@class GTLRMobileclient_BlukiiInfo;
@class GTLRMobileclient_BlukiiRequestInfo;
@class GTLRMobileclient_InfoBundle;
@class GTLRMobileclient_InfoBundleItem;
@class GTLRMobileclient_InfoBundleRequestInfo;
@class GTLRMobileclient_InfoPointV1;
@class GTLRMobileclient_InfoPointV2;
@class GTLRMobileclient_JsonMap;
@class GTLRMobileclient_OutputInfoV1;

// Generated comments include content from the discovery document; avoid them
// causing warnings since clang's checks are some what arbitrary.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdocumentation"

NS_ASSUME_NONNULL_BEGIN

// ----------------------------------------------------------------------------
// Constants - For some of the classes' properties below.

// ----------------------------------------------------------------------------
// GTLRMobileclient.InfoBundleItemType

/** Value: "BUNDLE" */
GTLR_EXTERN NSString * const kGTLRMobileclient_InfoBundleItemType_Bundle;
/** Value: "BUNDLE_ID" */
GTLR_EXTERN NSString * const kGTLRMobileclient_InfoBundleItemType_BundleId;
/** Value: "INFOPOINT" */
GTLR_EXTERN NSString * const kGTLRMobileclient_InfoBundleItemType_Infopoint;

// ----------------------------------------------------------------------------
// GTLRMobileclient.OutputInfoType

/** Value: "AUDIO" */
GTLR_EXTERN NSString * const kGTLRMobileclient_OutputInfoType_Audio;
/** Value: "HTML" */
GTLR_EXTERN NSString * const kGTLRMobileclient_OutputInfoType_Html;
/** Value: "MESSAGE" */
GTLR_EXTERN NSString * const kGTLRMobileclient_OutputInfoType_Message;
/** Value: "MOBYCARD" */
GTLR_EXTERN NSString * const kGTLRMobileclient_OutputInfoType_Mobycard;
/** Value: "PDF" */
GTLR_EXTERN NSString * const kGTLRMobileclient_OutputInfoType_Pdf;
/** Value: "VCARD" */
GTLR_EXTERN NSString * const kGTLRMobileclient_OutputInfoType_Vcard;
/** Value: "VIDEO" */
GTLR_EXTERN NSString * const kGTLRMobileclient_OutputInfoType_Video;
/** Value: "WIFI" */
GTLR_EXTERN NSString * const kGTLRMobileclient_OutputInfoType_Wifi;
/** Value: "YOUTUBE" */
GTLR_EXTERN NSString * const kGTLRMobileclient_OutputInfoType_Youtube;

/**
 *  GTLRMobileclient_BlukiiInfo
 */
@interface GTLRMobileclient_BlukiiInfo : GTLRObject

/**
 *  identifier
 *
 *  identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
 */
@property(nonatomic, copy, nullable) NSString *identifier;

@property(nonatomic, strong, nullable) GTLRMobileclient_InfoPointV2 *infoPoint;

@end


/**
 *  GTLRMobileclient_BlukiiInfoCollection
 *
 *  @note This class supports NSFastEnumeration and indexed subscripting over
 *        its "items" property.
 */
@interface GTLRMobileclient_BlukiiInfoCollection : GTLRCollectionObject

/**
 *  items
 *
 *  @note This property is used to support NSFastEnumeration and indexed
 *        subscripting on this class.
 */
@property(nonatomic, strong, nullable) NSArray<GTLRMobileclient_BlukiiInfo *> *items;

@end


/**
 *  GTLRMobileclient_BlukiiRequestInfo
 */
@interface GTLRMobileclient_BlukiiRequestInfo : GTLRObject

/**
 *  identifier
 *
 *  identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
 */
@property(nonatomic, copy, nullable) NSString *identifier;

/**
 *  timeStamp
 *
 *  Uses NSNumber of longLongValue.
 */
@property(nonatomic, strong, nullable) NSNumber *timeStamp;

@end


/**
 *  GTLRMobileclient_GetBlukiisInfoData
 */
@interface GTLRMobileclient_GetBlukiisInfoData : GTLRObject

@property(nonatomic, copy, nullable) NSString *appLabel;
@property(nonatomic, copy, nullable) NSString *applicationId;
@property(nonatomic, strong, nullable) NSArray<NSString *> *blukiiIds;
@property(nonatomic, strong, nullable) NSArray<GTLRMobileclient_BlukiiRequestInfo *> *blukiis;
@property(nonatomic, copy, nullable) NSString *deviceId;

@end


/**
 *  GTLRMobileclient_GetInfoBundlesData
 */
@interface GTLRMobileclient_GetInfoBundlesData : GTLRObject

@property(nonatomic, copy, nullable) NSString *applicationId;
@property(nonatomic, strong, nullable) NSArray<GTLRMobileclient_InfoBundleRequestInfo *> *infoBundles;

@end


/**
 *  GTLRMobileclient_InfoBundle
 */
@interface GTLRMobileclient_InfoBundle : GTLRObject

/**
 *  descriptionProperty
 *
 *  Remapped to 'descriptionProperty' to avoid NSObject's 'description'.
 */
@property(nonatomic, copy, nullable) NSString *descriptionProperty;

/**
 *  identifier
 *
 *  identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
 */
@property(nonatomic, copy, nullable) NSString *identifier;

@property(nonatomic, strong, nullable) NSArray<GTLRMobileclient_InfoBundleItem *> *infoBundleItems;

/**
 *  infoProviderBlocked
 *
 *  Uses NSNumber of boolValue.
 */
@property(nonatomic, strong, nullable) NSNumber *infoProviderBlocked;

/**
 *  infoProviderId
 *
 *  Uses NSNumber of longLongValue.
 */
@property(nonatomic, strong, nullable) NSNumber *infoProviderId;

/**
 *  itemsProtected
 *
 *  Uses NSNumber of boolValue.
 */
@property(nonatomic, strong, nullable) NSNumber *itemsProtected;

@property(nonatomic, strong, nullable) GTLRMobileclient_JsonMap *outputs;
@property(nonatomic, copy, nullable) NSString *replacedId;

/**
 *  valid
 *
 *  Uses NSNumber of boolValue.
 */
@property(nonatomic, strong, nullable) NSNumber *valid;

@end


/**
 *  GTLRMobileclient_InfoBundleCollection
 *
 *  @note This class supports NSFastEnumeration and indexed subscripting over
 *        its "items" property.
 */
@interface GTLRMobileclient_InfoBundleCollection : GTLRCollectionObject

/**
 *  items
 *
 *  @note This property is used to support NSFastEnumeration and indexed
 *        subscripting on this class.
 */
@property(nonatomic, strong, nullable) NSArray<GTLRMobileclient_InfoBundle *> *items;

@end


/**
 *  GTLRMobileclient_InfoBundleItem
 */
@interface GTLRMobileclient_InfoBundleItem : GTLRObject

/**
 *  downloadMaster
 *
 *  Uses NSNumber of boolValue.
 */
@property(nonatomic, strong, nullable) NSNumber *downloadMaster;

/**
 *  identifier
 *
 *  identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
 */
@property(nonatomic, copy, nullable) NSString *identifier;

@property(nonatomic, strong, nullable) GTLRMobileclient_InfoPointV2 *infoPoint;
@property(nonatomic, copy, nullable) NSString *type;

/**
 *  valid
 *
 *  Uses NSNumber of boolValue.
 */
@property(nonatomic, strong, nullable) NSNumber *valid;

@end


/**
 *  GTLRMobileclient_InfoBundleRequestInfo
 */
@interface GTLRMobileclient_InfoBundleRequestInfo : GTLRObject

@property(nonatomic, copy, nullable) NSString *infoBundleId;

/**
 *  infoProviderId
 *
 *  Uses NSNumber of longLongValue.
 */
@property(nonatomic, strong, nullable) NSNumber *infoProviderId;

@end


/**
 *  GTLRMobileclient_InfoPointV1
 */
@interface GTLRMobileclient_InfoPointV1 : GTLRObject

@property(nonatomic, copy, nullable) NSString *condition;

/**
 *  identifier
 *
 *  identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
 */
@property(nonatomic, copy, nullable) NSString *identifier;

@property(nonatomic, copy, nullable) NSString *imageWebUrl;

/**
 *  infoProviderId
 *
 *  Uses NSNumber of longLongValue.
 */
@property(nonatomic, strong, nullable) NSNumber *infoProviderId;

@property(nonatomic, copy, nullable) NSString *name;
@property(nonatomic, copy, nullable) NSString *nearbyIconUrl;
@property(nonatomic, strong, nullable) NSArray<GTLRMobileclient_OutputInfoV1 *> *outputInfos;

/**
 *  rssi
 *
 *  Uses NSNumber of intValue.
 */
@property(nonatomic, strong, nullable) NSNumber *rssi;

@end


/**
 *  GTLRMobileclient_InfoPointV1Collection
 *
 *  @note This class supports NSFastEnumeration and indexed subscripting over
 *        its "items" property.
 */
@interface GTLRMobileclient_InfoPointV1Collection : GTLRCollectionObject

/**
 *  items
 *
 *  @note This property is used to support NSFastEnumeration and indexed
 *        subscripting on this class.
 */
@property(nonatomic, strong, nullable) NSArray<GTLRMobileclient_InfoPointV1 *> *items;

@end


/**
 *  GTLRMobileclient_InfoPointV2
 */
@interface GTLRMobileclient_InfoPointV2 : GTLRObject

@property(nonatomic, strong, nullable) GTLRMobileclient_JsonMap *blukiiDescriptions;
@property(nonatomic, strong, nullable) NSArray<NSString *> *blukiis;
@property(nonatomic, copy, nullable) NSString *condition;

/**
 *  deactivated
 *
 *  Uses NSNumber of boolValue.
 */
@property(nonatomic, strong, nullable) NSNumber *deactivated;

/**
 *  deactivatedByAdmin
 *
 *  Uses NSNumber of boolValue.
 */
@property(nonatomic, strong, nullable) NSNumber *deactivatedByAdmin;

/**
 *  descriptionProperty
 *
 *  Remapped to 'descriptionProperty' to avoid NSObject's 'description'.
 */
@property(nonatomic, copy, nullable) NSString *descriptionProperty;

/**
 *  identifier
 *
 *  identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
 */
@property(nonatomic, copy, nullable) NSString *identifier;

@property(nonatomic, copy, nullable) NSString *imageWebUrl;
@property(nonatomic, strong, nullable) NSArray<GTLRMobileclient_InfoBundleItem *> *infoBundleItems;

/**
 *  infoProviderBlocked
 *
 *  Uses NSNumber of boolValue.
 */
@property(nonatomic, strong, nullable) NSNumber *infoProviderBlocked;

/**
 *  infoProviderId
 *
 *  Uses NSNumber of longLongValue.
 */
@property(nonatomic, strong, nullable) NSNumber *infoProviderId;

@property(nonatomic, copy, nullable) NSString *infoProviderName;
@property(nonatomic, copy, nullable) NSString *nearbyIconUrl;
@property(nonatomic, strong, nullable) GTLRMobileclient_JsonMap *outputInfos;
@property(nonatomic, copy, nullable) NSString *replacedId;

/**
 *  rssi
 *
 *  Uses NSNumber of intValue.
 */
@property(nonatomic, strong, nullable) NSNumber *rssi;

/**
 *  shortIdEnabled
 *
 *  Uses NSNumber of boolValue.
 */
@property(nonatomic, strong, nullable) NSNumber *shortIdEnabled;

@property(nonatomic, strong, nullable) GTLRMobileclient_JsonMap *shortUrls;
@property(nonatomic, copy, nullable) NSString *uniqueId;

@end


/**
 *  GTLRMobileclient_JsonMap
 */
@interface GTLRMobileclient_JsonMap : GTLRObject
@end


/**
 *  GTLRMobileclient_OutputInfoV1
 */
@interface GTLRMobileclient_OutputInfoV1 : GTLRObject

@property(nonatomic, copy, nullable) NSString *audioFileUrl;
@property(nonatomic, copy, nullable) NSString *imageWebUrl;
@property(nonatomic, copy, nullable) NSString *languageCode;
@property(nonatomic, copy, nullable) NSString *textToSpeech;
@property(nonatomic, copy, nullable) NSString *title;
@property(nonatomic, copy, nullable) NSString *type;
@property(nonatomic, copy, nullable) NSString *url;

@end


/**
 *  GTLRMobileclient_ReportInfoPointData
 */
@interface GTLRMobileclient_ReportInfoPointData : GTLRObject

@property(nonatomic, copy, nullable) NSString *applicationId;
@property(nonatomic, copy, nullable) NSString *infoPointId;
@property(nonatomic, copy, nullable) NSString *infoPointName;
@property(nonatomic, copy, nullable) NSString *infoPointPreviewUrl;

/**
 *  infoProviderId
 *
 *  Uses NSNumber of longLongValue.
 */
@property(nonatomic, strong, nullable) NSNumber *infoProviderId;

@property(nonatomic, copy, nullable) NSString *messageText;
@property(nonatomic, copy, nullable) NSString *outputInfoAudioFileUrl;
@property(nonatomic, copy, nullable) NSString *outputInfoLanguageCode;
@property(nonatomic, copy, nullable) NSString *outputInfoTextToSpeech;
@property(nonatomic, copy, nullable) NSString *outputInfoTitle;
@property(nonatomic, copy, nullable) NSString *outputInfoType;
@property(nonatomic, copy, nullable) NSString *outputInfoUrl;
@property(nonatomic, copy, nullable) NSString *senderEmail;
@property(nonatomic, copy, nullable) NSString *senderName;

/**
 *  timeStamp
 *
 *  Uses NSNumber of longLongValue.
 */
@property(nonatomic, strong, nullable) NSNumber *timeStamp;

@end


/**
 *  GTLRMobileclient_ReportInfoStatisticData
 */
@interface GTLRMobileclient_ReportInfoStatisticData : GTLRObject

@property(nonatomic, copy, nullable) NSString *applicationId;
@property(nonatomic, copy, nullable) NSString *blukiiId;
@property(nonatomic, copy, nullable) NSString *deviceId;

/**
 *  timeStamp
 *
 *  Uses NSNumber of longLongValue.
 */
@property(nonatomic, strong, nullable) NSNumber *timeStamp;

/**
 *  type
 *
 *  Uses NSNumber of intValue.
 */
@property(nonatomic, strong, nullable) NSNumber *type;

@end

NS_ASSUME_NONNULL_END

#pragma clang diagnostic pop
