// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   securebeacon/v1
// Description:
//   This is an API

#import "GTLRSecurebeaconObjects.h"
#import "GTLRSecurebeaconQuery.h"
#import "GTLRSecurebeaconService.h"
