// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   securebeacon/v1
// Description:
//   This is an API

#if GTLR_BUILT_AS_FRAMEWORK
  #import "GTLR/GTLRObject.h"
#else
  #import "GTLRObject.h"
#endif

#if GTLR_RUNTIME_VERSION != 3000
#error This file was generated by a different version of ServiceGenerator which is incompatible with this GTLR library source.
#endif

@class GTLRSecurebeacon_SecureBeacon;

// Generated comments include content from the discovery document; avoid them
// causing warnings since clang's checks are some what arbitrary.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdocumentation"

NS_ASSUME_NONNULL_BEGIN

/**
 *  GTLRSecurebeacon_Collection
 *
 *  @note This class supports NSFastEnumeration and indexed subscripting over
 *        its "items" property.
 */
@interface GTLRSecurebeacon_Collection : GTLRCollectionObject

/**
 *  items
 *
 *  @note This property is used to support NSFastEnumeration and indexed
 *        subscripting on this class.
 */
@property(nonatomic, strong, nullable) NSArray<GTLRSecurebeacon_SecureBeacon *> *items;

@end


/**
 *  GTLRSecurebeacon_SecureBeacon
 */
@interface GTLRSecurebeacon_SecureBeacon : GTLRObject

@property(nonatomic, copy, nullable) NSString *iBeaconMajor;
@property(nonatomic, copy, nullable) NSString *iBeaconMinor;

/**
 *  identifier
 *
 *  identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
 */
@property(nonatomic, copy, nullable) NSString *identifier;

@property(nonatomic, copy, nullable) NSString *secureBeaconResult;

@end


/**
 *  GTLRSecurebeacon_StringList
 */
@interface GTLRSecurebeacon_StringList : GTLRObject

@property(nonatomic, strong, nullable) NSArray<NSString *> *values;

@end

NS_ASSUME_NONNULL_END

#pragma clang diagnostic pop
