// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   securebeacon/v1
// Description:
//   This is an API

#if GTLR_BUILT_AS_FRAMEWORK
  #import "GTLR/GTLRQuery.h"
#else
  #import "GTLRQuery.h"
#endif

#if GTLR_RUNTIME_VERSION != 3000
#error This file was generated by a different version of ServiceGenerator which is incompatible with this GTLR library source.
#endif

@class GTLRSecurebeacon_StringList;

// Generated comments include content from the discovery document; avoid them
// causing warnings since clang's checks are some what arbitrary.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdocumentation"

NS_ASSUME_NONNULL_BEGIN

/**
 *  Parent class for other Securebeacon query classes.
 */
@interface GTLRSecurebeaconQuery : GTLRQuery

/** Selector specifying which fields to include in a partial response. */
@property(nonatomic, copy, nullable) NSString *fields;

@end

/**
 *  GTLRSecurebeaconQuery_SecureBeaconEndpointsApiGetSecureBeaconList
 *
 *  Method: securebeacon.secureBeaconEndpointsApi.getSecureBeaconList
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeSecurebeaconUserinfoEmail
 */
@interface GTLRSecurebeaconQuery_SecureBeaconEndpointsApiGetSecureBeaconList : GTLRSecurebeaconQuery
// Previous library name was
//   +[GTLQuerySecurebeacon queryForSecureBeaconEndpointsApiGetSecureBeaconList]

/**
 *  Fetches a @c GTLRSecurebeacon_Collection.
 *
 *  @return GTLRSecurebeaconQuery_SecureBeaconEndpointsApiGetSecureBeaconList
 */
+ (instancetype)query;

@end

/**
 *  GTLRSecurebeaconQuery_SecureBeaconEndpointsApiGetSecureBeacons
 *
 *  Method: securebeacon.secureBeaconEndpointsApi.getSecureBeacons
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeSecurebeaconUserinfoEmail
 */
@interface GTLRSecurebeaconQuery_SecureBeaconEndpointsApiGetSecureBeacons : GTLRSecurebeaconQuery
// Previous library name was
//   +[GTLQuerySecurebeacon queryForSecureBeaconEndpointsApiGetSecureBeaconsWithObject:]

/**
 *  Fetches a @c GTLRSecurebeacon_Collection.
 *
 *  @param object The @c GTLRSecurebeacon_StringList to include in the query.
 *
 *  @return GTLRSecurebeaconQuery_SecureBeaconEndpointsApiGetSecureBeacons
 */
+ (instancetype)queryWithObject:(GTLRSecurebeacon_StringList *)object;

@end

NS_ASSUME_NONNULL_END

#pragma clang diagnostic pop
