/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMobileclientGetOutputInfosData.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   mobileclient/v1
// Description:
//   This is an API
// Classes:
//   GTLMobileclientGetOutputInfosData (0 custom class methods, 2 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLMobileclientGetOutputInfosData
//

@interface GTLMobileclientGetOutputInfosData : GTLObject
@property (nonatomic, retain) NSArray *infoPointIds;  // of NSString
@property (nonatomic, copy) NSString *languageCode;
@end
