/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMobileclientOutputInfo.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   mobileclient/v1
// Description:
//   This is an API
// Classes:
//   GTLMobileclientOutputInfo (0 custom class methods, 6 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLMobileclientOutputInfo
//

@interface GTLMobileclientOutputInfo : GTLObject
@property (nonatomic, copy) NSString *audioFileUrl;
@property (nonatomic, copy) NSString *languageCode;
@property (nonatomic, copy) NSString *textToSpeech;
@property (nonatomic, copy) NSString *title;
@property (nonatomic, copy) NSString *type;
@property (nonatomic, copy) NSString *url;
@end
