/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMobileclientInfoPoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   mobileclient/v1
// Description:
//   This is an API
// Classes:
//   GTLMobileclientInfoPoint (0 custom class methods, 6 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLMobileclientOutputInfo;
@class GTLMobileclientPicture;

// ----------------------------------------------------------------------------
//
//   GTLMobileclientInfoPoint
//

@interface GTLMobileclientInfoPoint : GTLObject

// Remapped to 'descriptionProperty' to avoid NSObject's 'description'.
@property (nonatomic, copy) NSString *descriptionProperty;

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (nonatomic, copy) NSString *identifier;

@property (nonatomic, retain) NSNumber *isDeactivated;  // boolValue
@property (nonatomic, copy) NSString *name;
@property (nonatomic, retain) NSArray *outputInfos;  // of GTLMobileclientOutputInfo
@property (nonatomic, retain) GTLMobileclientPicture *picture;
@end
