/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMobileclient.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   mobileclient/v1
// Description:
//   This is an API

#import "GTLMobileclientConstants.h"

#import "GTLMobileclientGetOutputInfosData.h"
#import "GTLMobileclientInfoPoint.h"
#import "GTLMobileclientInfoPointCollection.h"
#import "GTLMobileclientInfoPointIds.h"
#import "GTLMobileclientJsonMap.h"
#import "GTLMobileclientNews.h"
#import "GTLMobileclientOutputInfo.h"
#import "GTLMobileclientPicture.h"

#import "GTLQueryMobileclient.h"
#import "GTLServiceMobileclient.h"
