/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMobileclientConstants.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   mobileclient/v1
// Description:
//   This is an API

#import <Foundation/Foundation.h>

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLDefines.h"
#else
  #import "GTLDefines.h"
#endif

// Authorization scope
// View your email address
GTL_EXTERN NSString * const kGTLAuthScopeMobileclientUserinfoEmail;  // "https://www.googleapis.com/auth/userinfo.email"

// GTLMobileclient - OutputInfoType
GTL_EXTERN NSString * const kGTLMobileclient_OutputInfoType_Html;  // "HTML"
GTL_EXTERN NSString * const kGTLMobileclient_OutputInfoType_Message;  // "MESSAGE"
GTL_EXTERN NSString * const kGTLMobileclient_OutputInfoType_Mobycard;  // "MOBYCARD"
GTL_EXTERN NSString * const kGTLMobileclient_OutputInfoType_Pdf;  // "PDF"
GTL_EXTERN NSString * const kGTLMobileclient_OutputInfoType_Vcard;  // "VCARD"
GTL_EXTERN NSString * const kGTLMobileclient_OutputInfoType_Wifi;  // "WIFI"
GTL_EXTERN NSString * const kGTLMobileclient_OutputInfoType_Youtube;  // "YOUTUBE"
