/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQueryMobileclient.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   mobileclient/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryMobileclient (5 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLMobileclientGetOutputInfosData;
@class GTLMobileclientInfoPointIds;

@interface GTLQueryMobileclient : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (nonatomic, copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (nonatomic, copy) NSString *infoPointId;
@property (nonatomic, copy) NSString *languageCode;

#pragma mark - "mobileClientApi" methods
// These create a GTLQueryMobileclient object.

// Method: mobileclient.mobileClientApi.getInfoPoint
//  Authorization scope(s):
//   kGTLAuthScopeMobileclientUserinfoEmail
// Fetches a GTLMobileclientInfoPoint.
+ (instancetype)queryForMobileClientApiGetInfoPointWithInfoPointId:(NSString *)infoPointId;

// Method: mobileclient.mobileClientApi.getInfoPoints
//  Authorization scope(s):
//   kGTLAuthScopeMobileclientUserinfoEmail
// Fetches a GTLMobileclientInfoPointCollection.
+ (instancetype)queryForMobileClientApiGetInfoPointsWithObject:(GTLMobileclientInfoPointIds *)object;

// Method: mobileclient.mobileClientApi.getNews
//  Authorization scope(s):
//   kGTLAuthScopeMobileclientUserinfoEmail
// Fetches a GTLMobileclientNews.
+ (instancetype)queryForMobileClientApiGetNewsWithLanguageCode:(NSString *)languageCode;

// Method: mobileclient.mobileClientApi.getOutputInfo
//  Authorization scope(s):
//   kGTLAuthScopeMobileclientUserinfoEmail
// Fetches a GTLMobileclientOutputInfo.
+ (instancetype)queryForMobileClientApiGetOutputInfoWithInfoPointId:(NSString *)infoPointId
                                                       languageCode:(NSString *)languageCode;

// Method: mobileclient.mobileClientApi.getOutputInfos
//  Authorization scope(s):
//   kGTLAuthScopeMobileclientUserinfoEmail
// Fetches a GTLMobileclientJsonMap.
+ (instancetype)queryForMobileClientApiGetOutputInfosWithObject:(GTLMobileclientGetOutputInfosData *)object;

@end
