// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   mobileclient/v1
// Description:
//   This is an API

#if GTLR_BUILT_AS_FRAMEWORK
  #import "GTLR/GTLRObject.h"
#else
  #import "GTLRObject.h"
#endif

#if GTLR_RUNTIME_VERSION != 3000
#error This file was generated by a different version of ServiceGenerator which is incompatible with this GTLR library source.
#endif

@class GTLRMobileclient_Blukii;
@class GTLRMobileclient_InfoPoint;
@class GTLRMobileclient_OutputInfo;

NS_ASSUME_NONNULL_BEGIN

// ----------------------------------------------------------------------------
// Constants - For some of the classes' properties below.

// ----------------------------------------------------------------------------
// GTLRMobileclient.OutputInfoType

/** Value: "AUDIO" */
GTLR_EXTERN NSString * const kGTLRMobileclient_OutputInfoType_Audio;
/** Value: "HTML" */
GTLR_EXTERN NSString * const kGTLRMobileclient_OutputInfoType_Html;
/** Value: "MESSAGE" */
GTLR_EXTERN NSString * const kGTLRMobileclient_OutputInfoType_Message;
/** Value: "MOBYCARD" */
GTLR_EXTERN NSString * const kGTLRMobileclient_OutputInfoType_Mobycard;
/** Value: "PDF" */
GTLR_EXTERN NSString * const kGTLRMobileclient_OutputInfoType_Pdf;
/** Value: "VCARD" */
GTLR_EXTERN NSString * const kGTLRMobileclient_OutputInfoType_Vcard;
/** Value: "VIDEO" */
GTLR_EXTERN NSString * const kGTLRMobileclient_OutputInfoType_Video;
/** Value: "WIFI" */
GTLR_EXTERN NSString * const kGTLRMobileclient_OutputInfoType_Wifi;
/** Value: "YOUTUBE" */
GTLR_EXTERN NSString * const kGTLRMobileclient_OutputInfoType_Youtube;

/**
 *  GTLRMobileclient_Blukii
 */
@interface GTLRMobileclient_Blukii : GTLRObject

/**
 *  identifier
 *
 *  identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
 */
@property(nonatomic, copy, nullable) NSString *identifier;

@end


/**
 *  GTLRMobileclient_GetBlukiisInfoData
 */
@interface GTLRMobileclient_GetBlukiisInfoData : GTLRObject

@property(nonatomic, copy, nullable) NSString *appLabel;
@property(nonatomic, strong, nullable) NSArray<NSString *> *blukiiIds;
@property(nonatomic, strong, nullable) NSArray<GTLRMobileclient_Blukii *> *blukiis;
@property(nonatomic, copy, nullable) NSString *deviceId;

@end


/**
 *  GTLRMobileclient_GetOutputInfosData
 */
@interface GTLRMobileclient_GetOutputInfosData : GTLRObject

@property(nonatomic, strong, nullable) NSArray<NSString *> *infoPointIds;
@property(nonatomic, copy, nullable) NSString *languageCode;

@end


/**
 *  GTLRMobileclient_InfoPoint
 */
@interface GTLRMobileclient_InfoPoint : GTLRObject

@property(nonatomic, copy, nullable) NSString *condition;

/**
 *  deactivated
 *
 *  Uses NSNumber of boolValue.
 */
@property(nonatomic, strong, nullable) NSNumber *deactivated;

/**
 *  deactivatedByAdmin
 *
 *  Uses NSNumber of boolValue.
 */
@property(nonatomic, strong, nullable) NSNumber *deactivatedByAdmin;

/**
 *  descriptionProperty
 *
 *  Remapped to 'descriptionProperty' to avoid NSObject's 'description'.
 */
@property(nonatomic, copy, nullable) NSString *descriptionProperty;

/**
 *  identifier
 *
 *  identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
 */
@property(nonatomic, copy, nullable) NSString *identifier;

@property(nonatomic, copy, nullable) NSString *imageWebUrl;

/**
 *  infoProviderId
 *
 *  Uses NSNumber of longLongValue.
 */
@property(nonatomic, strong, nullable) NSNumber *infoProviderId;

@property(nonatomic, copy, nullable) NSString *name;
@property(nonatomic, copy, nullable) NSString *notificationText;
@property(nonatomic, copy, nullable) NSString *notificationTo;
@property(nonatomic, strong, nullable) NSArray<GTLRMobileclient_OutputInfo *> *outputInfos;

/**
 *  rssi
 *
 *  Uses NSNumber of intValue.
 */
@property(nonatomic, strong, nullable) NSNumber *rssi;

@end


/**
 *  GTLRMobileclient_InfoPointCollection
 *
 *  @note This class supports NSFastEnumeration and indexed subscripting over
 *        its "items" property.
 */
@interface GTLRMobileclient_InfoPointCollection : GTLRCollectionObject

/**
 *  items
 *
 *  @note This property is used to support NSFastEnumeration and indexed
 *        subscripting on this class.
 */
@property(nonatomic, strong, nullable) NSArray<GTLRMobileclient_InfoPoint *> *items;

@end


/**
 *  GTLRMobileclient_InfoPointIds
 */
@interface GTLRMobileclient_InfoPointIds : GTLRObject

@property(nonatomic, strong, nullable) NSArray<NSString *> *values;

@end


/**
 *  GTLRMobileclient_JsonMap
 */
@interface GTLRMobileclient_JsonMap : GTLRObject
@end


/**
 *  GTLRMobileclient_News
 */
@interface GTLRMobileclient_News : GTLRObject

@property(nonatomic, copy, nullable) NSString *text;

@end


/**
 *  GTLRMobileclient_OutputInfo
 */
@interface GTLRMobileclient_OutputInfo : GTLRObject

@property(nonatomic, copy, nullable) NSString *audioFileUrl;
@property(nonatomic, copy, nullable) NSString *languageCode;
@property(nonatomic, copy, nullable) NSString *textToSpeech;
@property(nonatomic, copy, nullable) NSString *title;
@property(nonatomic, copy, nullable) NSString *type;
@property(nonatomic, copy, nullable) NSString *url;

@end


/**
 *  GTLRMobileclient_ReportInfoPointData
 */
@interface GTLRMobileclient_ReportInfoPointData : GTLRObject

@property(nonatomic, copy, nullable) NSString *applicationId;
@property(nonatomic, copy, nullable) NSString *infoPointId;
@property(nonatomic, copy, nullable) NSString *infoPointName;
@property(nonatomic, copy, nullable) NSString *infoPointPreviewUrl;

/**
 *  infoProviderId
 *
 *  Uses NSNumber of longLongValue.
 */
@property(nonatomic, strong, nullable) NSNumber *infoProviderId;

@property(nonatomic, copy, nullable) NSString *messageText;
@property(nonatomic, copy, nullable) NSString *outputInfoAudioFileUrl;
@property(nonatomic, copy, nullable) NSString *outputInfoLanguageCode;
@property(nonatomic, copy, nullable) NSString *outputInfoTextToSpeech;
@property(nonatomic, copy, nullable) NSString *outputInfoTitle;
@property(nonatomic, copy, nullable) NSString *outputInfoType;
@property(nonatomic, copy, nullable) NSString *outputInfoUrl;
@property(nonatomic, copy, nullable) NSString *senderEmail;
@property(nonatomic, copy, nullable) NSString *senderName;

/**
 *  timeStamp
 *
 *  Uses NSNumber of longLongValue.
 */
@property(nonatomic, strong, nullable) NSNumber *timeStamp;

@end

NS_ASSUME_NONNULL_END
