// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   auth/v1
// Description:
//   This is an API

#if GTLR_BUILT_AS_FRAMEWORK
  #import "GTLR/GTLRObject.h"
#else
  #import "GTLRObject.h"
#endif

#if GTLR_RUNTIME_VERSION != 3000
#error This file was generated by a different version of ServiceGenerator which is incompatible with this GTLR library source.
#endif

// Generated comments include content from the discovery document; avoid them
// causing warnings since clang's checks are some what arbitrary.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdocumentation"

NS_ASSUME_NONNULL_BEGIN

/**
 *  GTLRAuth_TokenData
 */
@interface GTLRAuth_TokenData : GTLRObject

@property(nonatomic, copy, nullable) NSString *expireDate;

/**
 *  expires
 *
 *  Uses NSNumber of longLongValue.
 */
@property(nonatomic, strong, nullable) NSNumber *expires;

@property(nonatomic, copy, nullable) NSString *role;
@property(nonatomic, copy, nullable) NSString *token;

@end

NS_ASSUME_NONNULL_END

#pragma clang diagnostic pop
