// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   mobileclient/v1
// Description:
//   This is an API

#if GTLR_BUILT_AS_FRAMEWORK
  #import "GTLR/GTLRQuery.h"
#else
  #import "GTLRQuery.h"
#endif

#if GTLR_RUNTIME_VERSION != 3000
#error This file was generated by a different version of ServiceGenerator which is incompatible with this GTLR library source.
#endif

@class GTLRMobileclient_GetBlukiisInfoData;
@class GTLRMobileclient_GetOutputInfosData;
@class GTLRMobileclient_InfoPointIds;
@class GTLRMobileclient_ReportInfoPointData;

NS_ASSUME_NONNULL_BEGIN

/**
 *  Parent class for other Mobileclient query classes.
 */
@interface GTLRMobileclientQuery : GTLRQuery

/** Selector specifying which fields to include in a partial response. */
@property(nonatomic, copy, nullable) NSString *fields;

@end

/**
 *  GTLRMobileclientQuery_MobileClientApiGetBlukiisInfo
 *
 *  Method: mobileclient.mobileClientApi.getBlukiisInfo
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeMobileclientUserinfoEmail
 */
@interface GTLRMobileclientQuery_MobileClientApiGetBlukiisInfo : GTLRMobileclientQuery
// Previous library name was
//   +[GTLQueryMobileclient queryForMobileClientApiGetBlukiisInfoWithObject:]

/**
 *  Fetches a @c GTLRMobileclient_InfoPointCollection.
 *
 *  @param object The @c GTLRMobileclient_GetBlukiisInfoData to include in the
 *    query.
 *
 *  @returns GTLRMobileclientQuery_MobileClientApiGetBlukiisInfo
 */
+ (instancetype)queryWithObject:(GTLRMobileclient_GetBlukiisInfoData *)object;

@end

/**
 *  GTLRMobileclientQuery_MobileClientApiGetInfoPoint
 *
 *  Method: mobileclient.mobileClientApi.getInfoPoint
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeMobileclientUserinfoEmail
 */
@interface GTLRMobileclientQuery_MobileClientApiGetInfoPoint : GTLRMobileclientQuery
// Previous library name was
//   +[GTLQueryMobileclient queryForMobileClientApiGetInfoPointWithinfoPointId:]

@property(nonatomic, copy, nullable) NSString *infoPointId;

/**
 *  Fetches a @c GTLRMobileclient_InfoPoint.
 *
 *  @param infoPointId NSString
 *
 *  @returns GTLRMobileclientQuery_MobileClientApiGetInfoPoint
 */
+ (instancetype)queryWithInfoPointId:(NSString *)infoPointId;

@end

/**
 *  GTLRMobileclientQuery_MobileClientApiGetInfoPoints
 *
 *  Method: mobileclient.mobileClientApi.getInfoPoints
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeMobileclientUserinfoEmail
 */
@interface GTLRMobileclientQuery_MobileClientApiGetInfoPoints : GTLRMobileclientQuery
// Previous library name was
//   +[GTLQueryMobileclient queryForMobileClientApiGetInfoPointsWithObject:]

/**
 *  Fetches a @c GTLRMobileclient_InfoPointCollection.
 *
 *  @param object The @c GTLRMobileclient_InfoPointIds to include in the query.
 *
 *  @returns GTLRMobileclientQuery_MobileClientApiGetInfoPoints
 */
+ (instancetype)queryWithObject:(GTLRMobileclient_InfoPointIds *)object;

@end

/**
 *  GTLRMobileclientQuery_MobileClientApiGetNews
 *
 *  Method: mobileclient.mobileClientApi.getNews
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeMobileclientUserinfoEmail
 */
@interface GTLRMobileclientQuery_MobileClientApiGetNews : GTLRMobileclientQuery
// Previous library name was
//   +[GTLQueryMobileclient queryForMobileClientApiGetNewsWithlanguageCode:]

@property(nonatomic, copy, nullable) NSString *languageCode;

/**
 *  Fetches a @c GTLRMobileclient_News.
 *
 *  @param languageCode NSString
 *
 *  @returns GTLRMobileclientQuery_MobileClientApiGetNews
 */
+ (instancetype)queryWithLanguageCode:(NSString *)languageCode;

@end

/**
 *  GTLRMobileclientQuery_MobileClientApiGetOutputInfo
 *
 *  Method: mobileclient.mobileClientApi.getOutputInfo
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeMobileclientUserinfoEmail
 */
@interface GTLRMobileclientQuery_MobileClientApiGetOutputInfo : GTLRMobileclientQuery
// Previous library name was
//   +[GTLQueryMobileclient queryForMobileClientApiGetOutputInfoWithinfoPointId:languageCode:]

@property(nonatomic, copy, nullable) NSString *infoPointId;

@property(nonatomic, copy, nullable) NSString *languageCode;

/**
 *  Fetches a @c GTLRMobileclient_OutputInfo.
 *
 *  @param infoPointId NSString
 *  @param languageCode NSString
 *
 *  @returns GTLRMobileclientQuery_MobileClientApiGetOutputInfo
 */
+ (instancetype)queryWithInfoPointId:(NSString *)infoPointId
                        languageCode:(NSString *)languageCode;

@end

/**
 *  GTLRMobileclientQuery_MobileClientApiGetOutputInfos
 *
 *  Method: mobileclient.mobileClientApi.getOutputInfos
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeMobileclientUserinfoEmail
 */
@interface GTLRMobileclientQuery_MobileClientApiGetOutputInfos : GTLRMobileclientQuery
// Previous library name was
//   +[GTLQueryMobileclient queryForMobileClientApiGetOutputInfosWithObject:]

/**
 *  Fetches a @c GTLRMobileclient_JsonMap.
 *
 *  @param object The @c GTLRMobileclient_GetOutputInfosData to include in the
 *    query.
 *
 *  @returns GTLRMobileclientQuery_MobileClientApiGetOutputInfos
 */
+ (instancetype)queryWithObject:(GTLRMobileclient_GetOutputInfosData *)object;

@end

/**
 *  GTLRMobileclientQuery_MobileClientApiReportInfoPoint
 *
 *  Method: mobileclient.mobileClientApi.reportInfoPoint
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeMobileclientUserinfoEmail
 */
@interface GTLRMobileclientQuery_MobileClientApiReportInfoPoint : GTLRMobileclientQuery
// Previous library name was
//   +[GTLQueryMobileclient queryForMobileClientApiReportInfoPointWithObject:]

/**
 *  Upon successful completion, the callback's object and error parameters will
 *  be nil. This query does not fetch an object.
 *
 *  @param object The @c GTLRMobileclient_ReportInfoPointData to include in the
 *    query.
 *
 *  @returns GTLRMobileclientQuery_MobileClientApiReportInfoPoint
 */
+ (instancetype)queryWithObject:(GTLRMobileclient_ReportInfoPointData *)object;

@end

NS_ASSUME_NONNULL_END
