// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   auth/v1
// Description:
//   This is an API

#if GTLR_BUILT_AS_FRAMEWORK
  #import "GTLR/GTLRQuery.h"
#else
  #import "GTLRQuery.h"
#endif

#if GTLR_RUNTIME_VERSION != 3000
#error This file was generated by a different version of ServiceGenerator which is incompatible with this GTLR library source.
#endif

// Generated comments include content from the discovery document; avoid them
// causing warnings since clang's checks are some what arbitrary.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdocumentation"

NS_ASSUME_NONNULL_BEGIN

/**
 *  Parent class for other Auth query classes.
 */
@interface GTLRAuthQuery : GTLRQuery

/** Selector specifying which fields to include in a partial response. */
@property(nonatomic, copy, nullable) NSString *fields;

@end

/**
 *  GTLRAuthQuery_AuthEndpointsApiDeleteToken
 *
 *  Method: auth.authEndpointsApi.deleteToken
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeAuthUserinfoEmail
 */
@interface GTLRAuthQuery_AuthEndpointsApiDeleteToken : GTLRAuthQuery
// Previous library name was
//   +[GTLQueryAuth queryForAuthEndpointsApiDeleteToken]

/**
 *  Upon successful completion, the callback's object and error parameters will
 *  be nil. This query does not fetch an object.
 *
 *  @return GTLRAuthQuery_AuthEndpointsApiDeleteToken
 */
+ (instancetype)query;

@end

/**
 *  GTLRAuthQuery_AuthEndpointsApiGetToken
 *
 *  Method: auth.authEndpointsApi.getToken
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeAuthUserinfoEmail
 */
@interface GTLRAuthQuery_AuthEndpointsApiGetToken : GTLRAuthQuery
// Previous library name was
//   +[GTLQueryAuth queryForAuthEndpointsApiGetToken]

/**
 *  Fetches a @c GTLRAuth_TokenData.
 *
 *  @return GTLRAuthQuery_AuthEndpointsApiGetToken
 */
+ (instancetype)query;

@end

NS_ASSUME_NONNULL_END

#pragma clang diagnostic pop
